export const AIRLINE_WEBSITES: Record<string, string> = {
  EK: "https://www.emirates.com",
  QR: "https://www.qatarairways.com",
  EY: "https://www.etihad.com",
  MS: "https://www.egyptair.com",
  KU: "https://www.kuwaitairways.com",
  SV: "https://www.saudiairlines.com",
  TK: "https://www.turkishairlines.com",
  LH: "https://www.lufthansa.com",
  BA: "https://www.britishairways.com",
  AF: "https://www.airfrance.com",
  KL: "https://www.klm.com",
  AA: "https://www.aa.com",
  DL: "https://www.delta.com",
  UA: "https://www.united.com",
  FR: "https://www.ryanair.com",
  U2: "https://www.easyjet.com",
  WY: "https://www.omanair.com",
  GF: "https://www.gulfair.com",
  FZ: "https://www.flydubai.com",
  G9: "https://www.airarabia.com",
  XY: "https://www.flynas.com",
  PC: "https://www.flypegasus.com",
  IB: "https://www.iberia.com",
  AZ: "https://www.ita-airways.com",
  OS: "https://www.austrian.com",
  LX: "https://www.swiss.com",
  SN: "https://www.brusselsairlines.com",
  SK: "https://www.sas.se",
  AY: "https://www.finnair.com",
  TP: "https://www.tapairportugal.com",
  CX: "https://www.cathaypacific.com",
  SQ: "https://www.singaporeair.com",
  MH: "https://www.malaysiaairlines.com",
  TG: "https://www.thaiairways.com",
  AI: "https://www.airindia.in",
  NH: "https://www.ana.co.jp",
  JL: "https://www.jal.com",
  ET: "https://www.ethiopianairlines.com",
  RJ: "https://www.rj.com",
  ME: "https://www.mea.com.lb",
  XQ: "https://www.sunexpress.com",
  W6: "https://www.wizzair.com",
  VY: "https://www.vueling.com",
  A3: "https://www.aegeanair.com",
  OA: "https://www.olympicair.com",
  RO: "https://www.tarom.ro",
  LO: "https://www.lot.com",
  OK: "https://www.csa.cz",
};

export function getAirlineWebsite(iataCode: string): string | null {
  return AIRLINE_WEBSITES[iataCode.toUpperCase()] ?? null;
}
