// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/luxury-green/Emerald.tsx": () => import("../components/mockups/luxury-green/Emerald.tsx"),
  "./components/mockups/luxury-green/Forest.tsx": () => import("../components/mockups/luxury-green/Forest.tsx"),
  "./components/mockups/luxury-green/Sage.tsx": () => import("../components/mockups/luxury-green/Sage.tsx")
};
